spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loci_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Rlaxodn0819!

  cloud:
    aws:
      s3:
        bucket: loci-assets-bucket
      region:
        static: ap-northeast-2
      stack:
        auto: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    show-sql: true
    properties.hibernate.format_sql: true

jwt:
  secret-key: uKa6]oJ^3K*0zQK.pF<1pmu.QfI7By)j[.Wl8?QJmAZ
  access-token-validity-seconds: 2592000

firebase:
  service-account-path: "firebase-service-account.json"

security:
  aes:
    secret-key: 627e20e89548c8cb3a6d9dc975a6f132deed141a3cc7c46d3aa82d421574f28b